server:
  port: ${SERVICE_SERVER_PORT}

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_URL}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
springdoc:
  packagesToScan: com.runapp.guildservice

eureka:
  client:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql:///${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${SQL_INSTANCE_NAME}
        enableIamAuth: true
        sslmode: disable
      maximum-pool-size: 6
      minimum-idle: 5
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: guild-service
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 6MB
  cloud:
    service-registry:
      auto-registration:
        enabled: false
    openfeign:
      client:
        config:
          storage-service:
            url: ${STORAGE_SERVICE_URL}
          story-manager-service:
            url: ${STORY-MANAGER_SERVICE_URL}
          profile-service:
            url: ${PROFILE_SERVICE_URL}

storage-directory: GuildService/